# Obtención de los datasets de los premios

# WebScraping

Recomendación de no ejecutar el siguiente código, ya que, empezará con las descargas del html. Para que no haga falta ejecutar esto también hemos subido el html obtenido. Además de que no funcionará ya que es necesario descargar selenium y chromedriver para hacer el webscraping bien.

In [ ]:
import os
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
import requests

#years = list(range(1956,2023))
years = list(range(1984,2023))

# install selenium chrome driver from https://chromedriver.chromium.org/downloads
# xattr -d com.apple.quarantine chromedriver
driver = webdriver.Chrome(executable_path="/Users/mhurben/upv/chromedriver")

for year in years:
    url = f'https://www.basketball-reference.com/awards/awards_{year}.html'
    
    driver.get(url)
    driver.execute_script("window.scrollTo(1,10000)")
    time.sleep(5)
    
    with open("./html/premios/{}.html".format(year), "w+") as f:
        f.write(driver.page_source)

# Sacamos los datsets

In [4]:
from bs4 import BeautifulSoup
import pandas as pd


dfs = []
years = list(range(1984,2023))

for year in years:
    with open("./html/premios/{}.html".format(year)) as f:
        page = f.read()
    
    soup = BeautifulSoup(page, 'html.parser')
    #print(soup)
    soup.find('tr', class_ = 'over_header').decompose()
    table = soup.find_all(id = 'div_mvp')
    player_df = pd.read_html(str(table))[0]
    player_df['Year'] = str(year)
    dfs.append(player_df)
    
df_mvps = pd.concat(dfs)

In [5]:
df_mvps

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
0,1,Larry Bird,27,BOS,52.0,652.0,760,0.858,79,38.3,...,10.1,6.6,1.8,0.9,0.492,0.247,0.888,13.6,0.215,1984
1,2,Bernard King,27,NYK,11.0,373.0,760,0.491,77,34.6,...,5.1,2.1,1.0,0.2,0.572,0.000,0.779,12.1,0.218,1984
2,3,Magic Johnson,24,LAL,5.0,305.0,760,0.401,67,38.3,...,7.3,13.1,2.2,0.7,0.565,0.207,0.810,10.2,0.191,1984
3,4,Kareem Abdul-Jabbar,36,LAL,3.0,153.0,760,0.201,80,32.8,...,7.3,2.6,0.7,1.8,0.578,0.000,0.723,8.9,0.163,1984
4,5,Isiah Thomas,22,DET,1.0,115.0,760,0.151,82,36.7,...,4.0,11.1,2.5,0.4,0.462,0.338,0.733,9.1,0.144,1984
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,8,Stephen Curry,33,GSW,0.0,4.0,1000,0.004,64,34.5,...,5.2,6.3,1.3,0.4,0.437,0.380,0.923,8.0,0.173,2022
8,9,Chris Paul,36,PHO,0.0,2.0,1000,0.002,65,32.9,...,4.4,10.8,1.9,0.3,0.493,0.317,0.837,9.4,0.210,2022
9,10T,DeMar DeRozan,32,CHI,0.0,1.0,1000,0.001,76,36.1,...,5.2,4.9,0.9,0.3,0.504,0.352,0.877,8.8,0.154,2022
10,10T,Kevin Durant,33,BRK,0.0,1.0,1000,0.001,55,37.2,...,7.4,6.4,0.9,0.9,0.518,0.383,0.910,8.4,0.198,2022
11,10T,LeBron James,37,LAL,0.0,1.0,1000,0.001,56,37.2,...,8.2,6.2,1.3,1.1,0.524,0.359,0.756,7.5,0.172,2022

In [7]:
from bs4 import BeautifulSoup
import pandas as pd


dfs = []
years = list(range(1984,2023))

for year in years:
    with open("./html/premios/{}.html".format(year)) as f:
        page = f.read()
    
    soup = BeautifulSoup(page, 'html.parser')
    #print(soup)
    #soup.find('tr', class_ = 'over_header').decompose()
    table = soup.find_all(id = 'div_roy')
    player_df = pd.read_html(str(table))[0]
    player_df['Year'] = str(year)
    dfs.append(player_df)
    
df_roy = pd.concat(dfs)

In [8]:
df_roy.columns = df_roy.columns.droplevel()

In [9]:
df_roy

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,
0,1,Ralph Sampson,23,HOU,76.0,76.0,76,1.000,82,32.8,...,11.1,2.0,0.9,2.4,0.523,0.250,0.661,6.0,0.108,1984
0,1,Michael Jordan,21,CHI,57.5,57.5,78,0.737,82,38.3,...,6.5,5.9,2.4,0.8,0.515,0.173,0.845,14.0,0.213,1985
1,2,Hakeem Olajuwon,22,HOU,20.5,20.5,78,0.263,82,35.5,...,11.9,1.4,1.2,2.7,0.538,NaN,0.613,10.2,0.168,1985
0,1,Patrick Ewing,23,NYK,36.0,36.0,78,0.462,50,35.4,...,9.0,2.0,1.1,2.1,0.474,0.000,0.739,3.1,0.084,1986
1,2,Xavier McDaniel,22,SEA,16.5,16.5,78,0.212,82,33.0,...,8.0,2.4,1.2,0.5,0.490,0.200,0.687,5.1,0.091,1986
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,2,Evan Mobley,20,CLE,43.0,363.0,500,0.726,69,33.8,...,8.3,2.5,0.8,1.7,0.508,0.250,0.663,5.2,0.107,2022
2,3,Cade Cunningham,20,DET,9.0,153.0,500,0.306,64,32.6,...,5.5,5.6,1.2,0.7,0.416,0.314,0.845,-0.5,-0.011,2022
3,4,Jalen Green,19,HOU,0.0,3.0,500,0.006,67,31.9,...,3.4,2.6,0.7,0.3,0.426,0.343,0.797,0.7,0.015,2022
4,5,Franz Wagner,20,ORL,0.0,2.0,500,0.004,79,30.7,...,4.5,2.9,0.9,0.4,0.468,0.354,0.863,4.0,0.079,2022
5,6,Herbert Jones,23,NOP,0.0,1.0,500,0.002,78,29.9,...,3.8,2.1,1.7,0.8,0.476,0.337,0.840,4.6,0.096,2022

In [10]:
from bs4 import BeautifulSoup
import pandas as pd


dfs = []
years = list(range(1984,2023))

for year in years:
    with open("./html/premios/{}.html".format(year)) as f:
        page = f.read()
    
    soup = BeautifulSoup(page, 'html.parser')
    #print(soup)
    #soup.find('tr', class_ = 'over_header').decompose()
    table = soup.find(id = 'div_dpoy')
    player_df = pd.read_html(str(table))[0]
    player_df['Year'] = str(year)
    dfs.append(player_df)
    
df_dpoy = pd.concat(dfs)

In [11]:
df_dpoy.columns = df_dpoy.columns.droplevel()

In [12]:
df_dpoy

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,...,BLK,FG%,3P%,FT%,WS,WS/48,DWS,DBPM,DRtg,
0,1,Sidney Moncrief,26,MIL,19.0,19.0,76,0.250,79,38.9,...,0.3,0.498,0.278,0.848,12.7,0.198,4.2,0.4,105,1984
1,2,Mark Eaton,27,UTA,14.0,14.0,76,0.184,82,26.1,...,4.3,0.466,0.000,0.593,3.7,0.084,3.5,3.7,102,1984
2,3,Dennis Johnson,29,BOS,7.0,7.0,76,0.092,80,33.3,...,0.7,0.437,0.125,0.852,5.7,0.102,3.2,0.6,106,1984
3,4T,Maurice Cheeks,27,PHI,5.0,5.0,76,0.066,75,33.3,...,0.3,0.550,0.400,0.733,7.3,0.141,3.4,1.6,105,1984
4,4T,Michael Cooper,27,LAL,5.0,5.0,76,0.066,82,29.1,...,0.8,0.497,0.314,0.838,6.5,0.130,2.6,1.7,107,1984
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6,7,Robert Williams,24,BOS,1.0,8.0,500,0.016,61,29.6,...,2.2,0.736,0.000,0.722,9.9,0.262,3.9,3.1,102,2022
7,8,Jrue Holiday,31,MIL,0.0,6.0,500,0.012,67,32.9,...,0.4,0.501,0.411,0.761,6.9,0.150,2.4,0.3,112,2022
8,9,Al Horford,35,BOS,0.0,3.0,500,0.006,69,29.1,...,1.3,0.467,0.336,0.842,7.6,0.181,3.8,2.9,104,2022
9,10,Draymond Green,31,GSW,0.0,2.0,500,0.004,46,28.9,...,1.1,0.525,0.296,0.659,3.6,0.131,2.8,4.6,103,2022
10,11,Matisse Thybulle,24,PHI,0.0,1.0,500,0.002,66,25.5,...,1.1,0.500,0.313,0.791,3.7,0.107,2.5,3.3,108,2022

In [13]:
from bs4 import BeautifulSoup
import pandas as pd


dfs = []
years = list(range(1984,2023))

for year in years:
    with open("./html/premios/{}.html".format(year)) as f:
        page = f.read()
    
    soup = BeautifulSoup(page, 'html.parser')
    #print(soup)
    soup.find('tr', class_ = 'over_header').decompose()
    table = soup.find(id = 'div_smoy')
    player_df = pd.read_html(str(table))[0]
    player_df['Year'] = str(year)
    dfs.append(player_df)
    
df_smoy = pd.concat(dfs)

In [14]:
df_smoy.columns = df_smoy.columns.droplevel()

In [15]:
df_smoy

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,
0,1,Kevin McHale,26,BOS,59.0,59.0,76,0.776,82,31.4,...,7.4,1.3,0.3,1.5,0.556,0.333,0.765,10.5,0.196,1984
1,2,John Drew,29,UTA,14.0,14.0,76,0.184,81,22.2,...,4.2,1.7,1.1,0.0,0.479,0.273,0.778,4.5,0.121,1984
2,3T,Kenny Carr,28,POR,1.0,1.0,76,0.013,82,29.9,...,7.8,1.9,0.8,0.4,0.561,0.000,0.673,6.7,0.131,1984
3,3T,Phil Hubbard,27,CLE,1.0,1.0,76,0.013,80,22.5,...,4.8,1.1,0.9,0.1,0.511,0.000,0.739,4.6,0.124,1984
4,3T,Bobby Jones,32,PHI,1.0,1.0,76,0.013,75,23.5,...,4.3,2.5,1.4,1.4,0.523,0.000,0.784,6.0,0.163,1984
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8,9,Montrezl Harrell,28,TOT,0.0,3.0,500,0.006,71,23.1,...,6.1,2.0,0.4,0.6,0.645,0.235,0.716,7.3,0.213,2022
9,10,Immanuel Quickley,22,NYK,0.0,2.0,500,0.004,78,23.1,...,3.2,3.5,0.7,0.0,0.392,0.346,0.881,4.2,0.113,2022
10,11T,Brandon Clarke,25,MEM,0.0,1.0,500,0.002,64,19.5,...,5.3,1.3,0.6,1.1,0.644,0.227,0.654,6.3,0.241,2022
11,11T,Tyus Jones,25,MEM,0.0,1.0,500,0.002,73,21.2,...,2.4,4.4,0.9,0.0,0.451,0.390,0.818,5.1,0.158,2022
12,11T,Maxi Kleber,30,DAL,0.0,1.0,500,0.002,59,24.6,...,5.9,1.2,0.5,1.0,0.398,0.325,0.708,3.0,0.098,2022

In [ ]:
df_mvps.to_csv('mvps.csv', sep = ';')

In [27]:
df_roy.to_csv('roy.csv', sep = ';')
df_dpoy.to_csv('dpoy.csv', sep = ';')
df_smoy.to_csv('smoy.csv', sep = ';')