# Obtención de los DataSets de los equipos

## WebScraping

Recomendación de no ejecutar el siguiente código, ya que, empezará con las descargas del html. Para que no haga falta ejecutar esto también hemos subido el html obtenido.

In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import time

url_start = 'https://www.basketball-reference.com/teams/BOS/stats_basic_totals.html#stats'

teams = ['BOS', 'MIL','PHI', 'CLE', 'NOH', 'MIA', 'NYK', 'ATL', 'CHI', 'TOR', 'WAS','IND', 'ORL', 'CHA', 'DET','DEN', 
         'MEM', 'SAC', 'DAL', 'PHO', 'LAC', 'NJN', 'MIN', 'GSW', 'POR', 'UTA', 'OKC', 'LAL', 'SAS', 'HOU']
#years = list(range(1947,2023))
#teams = ['NOH', 'HOU', 'BRK']
#equipos = ['NOH', 'NJN',]
#years = ['2022']

#teams = ['CHA']

for team in teams:
    print(team)
    url = f'https://www.basketball-reference.com/teams/{team}/stats_basic_totals.html#stats'
    data = requests.get(url)
    with open(f'./html/dataframeEquipos/{team}.html', 'w+') as f:
        f.write(data.text)
    time.sleep(15)

BOS
MIL
PHI
CLE
NOH
MIA
NYK
ATL
CHI
TOR
WAS
IND
ORL
CHA
DET
DEN
MEM
SAC
DAL
PHO
LAC
NJN
MIN
GSW
POR
UTA
OKC
LAL
SAS
HOU

## Obtención del DataSet

In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import time

teams = ['BOS', 'MIL','PHI', 'CLE', 'MIA', 'NYK', 'ATL', 'CHI', 'TOR', 'WAS','IND', 'ORL', 'CHA', 'DET','DEN', 
         'MEM', 'SAC', 'DAL', 'PHO', 'LAC', 'MIN', 'GSW', 'POR', 'UTA', 'OKC', 'LAL', 'SAS', 'HOU', 'NJN', 'NOH']

df = []
#teams = ['NJN', 'NOH']

for team in teams:
    #print(team)
    with open(f'./html/dataframeEquipos/{team}.html') as f:
            page = f.read()
    soup = BeautifulSoup(page, 'html.parser')
    table = soup.find(id = 'stats')
    nba_stats = pd.read_html(str(table))[0]
    nba_stats['Team'] = team
    nba_stats['Year'] = nba_stats['Season'].str.slice(0,4)
    df.append(nba_stats)
    
    
nba_df = pd.concat(df)

In [2]:
nba_df.head(50)

,Season,Lg,Tm,W,L,Finish,Unnamed: 6,Age,Ht.,Wt.,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Team,Year
0,2022-23,NBA,BOS,57,25,1,NaN,27.4,6-6,222,...,2921,3717,2186,521,430,1095,1542,9671,BOS,2022
1,2021-22,NBA,BOS,51,31,1,NaN,26.1,6-5,218,...,2915,3778,2036,591,478,1118,1521,9164,BOS,2021
2,2020-21,NBA,BOS,36,36,4,NaN,25.1,6-5,220,...,2421,3186,1689,556,383,1012,1471,8109,BOS,2020
3,2019-20,NBA,BOS,48,24,2,NaN,25.3,6-5,221,...,2549,3317,1655,595,406,995,1553,8183,BOS,2019
4,2018-19,NBA,BOS,49,33,3,NaN,25.7,6-6,221,...,2849,3653,2155,706,435,1052,1670,9216,BOS,2018
5,2017-18,NBA,BOS,55,27,2,NaN,24.7,6-6,221,...,2878,3645,1842,604,373,1149,1618,8529,BOS,2017
6,2016-17,NBA,BOS,53,29,1,NaN,25.9,6-5,219,...,2698,3442,2069,617,340,1088,1686,8857,BOS,2016
7,2015-16,NBA,BOS,48,34,2,NaN,25.2,6-5,220,...,2733,3683,1981,752,348,1127,1796,8669,BOS,2015
8,2014-15,NBA,BOS,40,42,2,NaN,25.0,6-6,221,...,2685,3595,2009,674,294,1133,1738,8312,BOS,2014
9,2013-14,NBA,BOS,25,57,4,NaN,25.4,6-6,221,...,2505,3485,1726,584,343,1261,1743,7892,BOS,2013
10,2012-13,NBA,BOS,41,40,3,NaN,29.1,6-6,214,...,2533,3187,1843,667,365,1181,1717,7818,BOS,2012
11,2011-12,NBA,BOS,39,27,1,NaN,29.3,6-6,213,...,2051,2560,1557,498,362,979,1315,6062,BOS,2011
12,2010-11,NBA,BOS,56,26,1,NaN,29.5,6-6,223,...,2542,3181,1921,676,344,1195,1678,7913,BOS,2010
13,2009-10,NBA,BOS,50,32,1,NaN,29.4,6-6,219,...,2449,3165,1930,701,402,1219,1816,8136,BOS,2009
14,2008-09,NBA,BOS,62,20,1,NaN,27.8,6-6,222,...,2586,3455,1862,621,387,1280,1897,8275,BOS,2008
15,2007-08,NBA,BOS,66,16,1,NaN,27.9,6-6,220,...,2615,3445,1833,696,379,1246,1864,8245,BOS,2007
16,2006-07,NBA,BOS,24,58,5,NaN,23.5,6-6,221,...,2391,3309,1630,589,382,1350,1971,7857,BOS,2006
17,2005-06,NBA,BOS,33,49,3,NaN,25.3,6-7,227,...,2432,3245,1716,578,422,1359,2033,8033,BOS,2005
18,2004-05,NBA,BOS,45,37,1,NaN,27.1,6-7,218,...,2438,3347,1810,667,423,1297,2000,8304,BOS,2004
19,2003-04,NBA,BOS,36,46,4,NaN,26.4,6-7,218,...,2440,3291,1683,770,331,1332,1837,7811,BOS,2003
20,Season,Lg,Tm,W,L,Finish,NaN,Age,Ht.,Wt.,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,BOS,Seas
21,2002-03,NBA,BOS,44,38,3,NaN,26.9,6-6,218,...,2471,3320,1575,720,303,1147,1758,7599,BOS,2002
22,2001-02,NBA,BOS,49,33,2,NaN,26.2,6-6,220,...,2570,3461,1722,793,292,1114,1776,7901,BOS,2001
23,2000-01,NBA,BOS,36,46,5,NaN,25.9,6-6,221,...,2367,3264,1708,769,336,1285,1952,7759,BOS,2000
24,1999-00,NBA,BOS,35,47,5,NaN,25.4,6-6,218,...,2420,3528,1741,795,286,1259,2223,8146,BOS,1999
25,1998-99,NBA,BOS,19,31,5,NaN,24.3,6-6,215,...,1458,2138,1073,453,255,807,1193,4650,BOS,1998
26,1997-98,NBA,BOS,36,46,6,NaN,23.9,6-6,209,...,2044,3240,1816,987,366,1330,2203,7864,BOS,1997
27,1996-97,NBA,BOS,15,67,7,NaN,26.1,6-6,211,...,2188,3283,1792,810,315,1342,1915,8248,BOS,1996
28,1995-96,NBA,BOS,33,49,5,NaN,26.3,6-5,208,...,2427,3477,1792,653,406,1302,2041,8495,BOS,1995
29,1994-95,NBA,BOS,35,47,3,NaN,27.2,6-6,207,...,2320,3476,1783,612,361,1305,1975,8428,BOS,1994
30,1993-94,NBA,BOS,32,50,5,NaN,27.8,6-6,204,...,2380,3417,1928,674,440,1242,1849,8267,BOS,1993
31,1992-93,NBA,BOS,48,34,2,NaN,28.6,6-6,206,...,2436,3512,1999,647,458,1174,1862,8502,BOS,1992
32,1991-92,NBA,BOS,51,31,1,NaN,29.2,6-6,207,...,2583,3678,2072,636,484,1165,1686,8745,BOS,1991
33,1990-91,NBA,BOS,56,26,1,NaN,28.2,6-7,205,...,2697,3785,2160,672,565,1320,1695,9145,BOS,1990
34,1989-90,NBA,BOS,52,30,2,NaN,30.2,6-7,209,...,2707,3773,2423,539,455,1256,1717,9023,BOS,1989
35,1988-89,NBA,BOS,42,40,3,NaN,28.5,6-7,204,...,2442,3621,2189,639,418,1336,1876,8958,BOS,1988
36,1987-88,NBA,BOS,57,25,1,NaN,29.8,6-7,205,...,2440,3370,2448,620,415,1304,1804,9315,BOS,1987
37,1986-87,NBA,BOS,59,23,1,NaN,29.4,6-7,205,...,2585,3518,2421,561,526,1300,1710,9237,BOS,1986
38,1985-86,NBA,BOS,67,15,1,NaN,29.3,6-7,204,...,2753,3807,2387,641,511,1360,1756,9359,BOS,1985
39,1984-85,NBA,BOS,63,19,1,NaN,28.5,6-7,205,...,2630,3746,2287,645,414,1332,1781,9412,BOS,1984
40,1983-84,NBA,BOS,62,20,1,NaN,28.0,6-7,204,...,2538,3697,2122,673,430,1420,1949,9194,BOS,1983
41,Season,Lg,Tm,W,L,Finish,NaN,Age,Ht.,Wt.,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,BOS,Seas
42,1982-83,NBA,BOS,56,26,2,NaN,27.3,6-6,201,...,2532,3805,2216,789,521,1541,2062,9191,BOS,1982
43,1981-82,NBA,BOS,63,19,1,NaN,27.3,6-7,202,...,2489,3742,2126,652,568,1452,2014,9180,BOS,1981
44,1980-81,NBA,BOS,62,20,1,NaN,27.0,6-7,200,...,2424,3579,2202,683,594,1577,1990,9008,BOS,1980
45,1979-80,NBA,BOS,61,21,1,NaN,27.3,6-6,201,...,2457,3684,2198,809,308,1539,1974,9303,BOS,1979
46,1978-79,NBA,BOS,29,53,5,NaN,27.5,6-6,202,...,2396,3515,1995,710,283,1713,1977,8874,BOS,1978
47,1977-78,NBA,BOS,32,50,3,NaN,29.7,6-6,207,...,2850,4085,1969,643,295,1652,2033,8670,BOS,1977
48,1976-77,NBA,BOS,44,38,2,NaN,28.7,6-6,208,...,2966,4207,2010,506,263,1673,2039,8572,BOS,1976
49,1975-76,NBA,BOS,54,28,1,NaN,29.0,6-5,203,...,2972,4341,1980,561,260,1609,2002,8708,BOS,1975

In [4]:
nba_teams = nba_df[~nba_df['Tm'].str.contains('Tm')]

In [5]:
del(nba_teams['Unnamed: 6'])

In [6]:
del(nba_teams['Unnamed: 10'])

In [7]:
del(nba_teams['Tm'])

In [8]:
nba_teams

,Season,Lg,W,L,Finish,Age,Ht.,Wt.,G,MP,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Team,Year
0,2022-23,NBA,57,25,1,27.4,6-6,222,82,19980,...,2921,3717,2186,521,430,1095,1542,9671,BOS,2022
1,2021-22,NBA,51,31,1,26.1,6-5,218,82,19905,...,2915,3778,2036,591,478,1118,1521,9164,BOS,2021
2,2020-21,NBA,36,36,4,25.1,6-5,220,72,17380,...,2421,3186,1689,556,383,1012,1471,8109,BOS,2020
3,2019-20,NBA,48,24,2,25.3,6-5,221,72,17430,...,2549,3317,1655,595,406,995,1553,8183,BOS,2019
4,2018-19,NBA,49,33,3,25.7,6-6,221,82,19780,...,2849,3653,2155,706,435,1052,1670,9216,BOS,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16,2006-07,NBA,39,43,4,26.4,6-6,214,82,19880,...,2512,3537,1537,522,347,1187,1620,7833,NOH,2006
17,2005-06,NBA,38,44,4,26.3,6-6,212,82,19805,...,2379,3297,1519,611,311,1095,1786,7611,NOH,2005
18,2004-05,NBA,18,64,5,27.5,6-6,219,82,19930,...,2281,3300,1724,550,310,1217,1883,7252,NOH,2004
19,2003-04,NBA,41,41,3,30.3,6-6,219,82,19830,...,2418,3509,1716,708,346,1228,1715,7529,NOH,2003
21,2002-03,NBA,47,35,3,29.1,6-6,223,82,19905,...,2475,3572,1807,656,394,1212,1769,7699,NOH,2002

In [9]:
nba_teams.to_csv('NbaFullTeams.csv', sep = ';')